language: csharp
solution: GraceAttorney.sln

jobs:
  include:
    - os: linux
      mono: latest
    - os: windows
      mono: none

#install:
#  - msbuild -t:restore

script:
  - msbuild /p:Configuration=Release GraceAttorney.sln
