name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./GraceAttorney.Core.sln --configuration Release --no-restore -o release_build
    - name: Upload 
      uses: actions/upload-artifact@v2
      with:
        name: GraceAttorney.Core
        path: release_build
