name: Mono on Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Build project with Mono
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/code -v ${{ github.workspace }}/built:/srv/code/built \
         mono:latest bin/bash -c \
         "cd /srv/code && nuget restore GraceAttorney.Framework.sln && msbuild GraceAttorney.Framework.sln /p:Configuration=Release && mv GraceAttorney/bin/Release/net461/ /srv/code/built"
         
    - name: Upload built project
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: GraceAttorney-Mono
        # A file, directory or wildcard pattern that describes what to upload
        path: built
